### ISSUE TITLE
create table for storing GET and POST for localMemory

### ISSUE THREAD

**Issue by TartuDen** [TartuDen/BMR_Generator#10]

**Comment by TartuDen** [comment]
```
export class LocalMemory {
    constructor(projectName="", tp="", version="", equipment=[], reagents=[]) {
        this.projectName = projectName;
        this.tp = tp;
        this.version = version;
        this.equipment = equipment;
        this.reagents = reagents;
    }
}
```
this class needs to have GET and POST endpoint references to corresponding BR

**Comment by TartuDen** [comment]
localMem:  LocalMemory {
  projectName: 'tile',
  tp: 'tp.1',
  version: '3.0',
  equipment: [
    { eq_name: 'balancesid1_0', eq_code: '007-1' },
    { eq_name: 'balancesid2_0', eq_code: '007-10' },
    { eq_name: 'm_pumpid1_3', eq_code: '001-22' },
    { eq_name: 'reactorid1_7', eq_code: '002-11' },
    { eq_name: 'reactorid2_7', eq_code: '002-10' }
  ],
  reagents: [
    Reagent { reag_id: 'reagent0', reag_name: 'aaa', reag_amount: '1' }
  ]
}

**Comment by Pomog** [comment]
[parameter-rest-controller](http://localhost:8085/swagger-ui/index.html#/parameter-rest-controller)

**Comment by Pomog** [comment]
[parameter-rest-controller](http://localhost:8085/swagger-ui/index.html#/parameter-rest-controller)
Created
