### ISSUE TITLE
problem with /processInitialInfo

### ISSUE THREAD

**Issue by TartuDen** [TartuDen/BMR_Generator#12]

**Comment by TartuDen** [comment]
I have one object stored in GET /processInitialInfo

{
    "projectName": "tile",
    "tp": "tp.2",
    "version": "1.0",
    "equipmentSet": [],
    "reagentSet": []
}

I do DELETE /http://localhost:8085/processInitialInfo/tile/tp.2/1.0

successfully

then POST http://localhost:8085/processInitialInfo
{
  "projectName": "tile",
  "tp": "tp.2",
  "version": "1.0",
  "equipment": [
    {
      "eq_name": "reactorid1_7",
      "eq_code": "002-14"
    }
  ],
  "reagents": [
    {
      "reag_id": "reagent1",
      "reag_name": "aaa",
      "reag_amount": "1"
    }
  ]
}

then do again
GET //processInitialInfo

and get same, no equipmentSet and reagentSet...
{
    "projectName": "tile",
    "tp": "tp.2",
    "version": "1.0",
    "equipmentSet": [],
    "reagentSet": []
}

**Comment by Pomog** [comment]
Use
```
{
    "projectName": "SampleProject7",
    "tp": "SampleTP",
    "version": "1.0",
    "equipmentSet": [
        {
            "code": "EQ1",
            "name": "Equipment 1"
        },
        {
            "code": "EQ2",
            "name": "Equipment 2"
        }
    ],
    "reagentSet": [
        {
            "tableID": "R1",
            "name": "Reagent 1"
        },
        {
            "tableID": "R2",
            "name": "Reagent 2"
        }
    ]
}
```
